### ISSUE TITLE
Can't ask for anything but public rolls

### ISSUE THREAD

**Issue by HonzoNebro** [kakaroto/fvtt-module-lmrtfy#12]
There is no longer an option to ask for a private roll, no error on console log
![image](https://user-images.githubusercontent.com/5500663/84543686-1b6bb100-acfc-11ea-930d-6c44dd49cf70.png)

![image](https://user-images.githubusercontent.com/5500663/84543674-127adf80-acfc-11ea-82b5-093574ba32df.png)

**Comment by kakaroto** [comment]
This was fixed in 2fc86715ccb8821c7484ae28c57b57ec599ed31c
About to make a release in a few minutes...

**Comment by HonzoNebro** [comment]
Oops, thanks!
