### ISSUE TITLE
Game systems compatible?

### ISSUE THREAD

**Issue by renkhal** [kakaroto/fvtt-module-lmrtfy#22]
Does this not work with Pathfinder 2e? I wanted to use it in conjunction with Trigger Happy, but it's not showing up on my Modules list to activate it.

**Comment by kakaroto** [comment]
It's dnd5e specific only, as it lists the dnd5e skills, abilities, saving throws, and uses the dnd5e system's API to make those rolls.
I don't plan on adding support for another system, but I'd be willing to merge such a feature if someone else implements it.
