### ISSUE TITLE
initiative ignores alert feat

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/fvtt-module-lmrtfy#23]
If using alert feat, initiative rolls +5 in dnd5e, but not with LMRTFY.
Also check if initiative can/should be added to combat tracker.

**Comment by LimpingNinja** [comment]
`game.system.data.initiative: "1d20 + @abilities.dex.mod + @attributes.init.value + (@abilities.dex.value / 100)"`

This is currently missing @attributes.init.bonus which is what is set when using the Alert feat. So adding that to the this._makeDiceRoll call should solve for it.

Additionally this will also miss out on Jack of All Trades and Remarkable Athlete.

actor.data.flags.jackOfAllTrades == true -> Math.floor(0.5 * data.attributes.prof);
actor.data.flags.remarkableAthlete == true ->  Math.ceil(0.5 * data.attributes.prof);

**Comment by LimpingNinja** [comment]
This looks like it will be a little more difficult to handle in a meaningful manner. If you just want to support the 'Alert' feat as general, then just adding + @attributes.init.bonus to the roll will work, this will also work for PF2e, it just won't 100% match the internal initiative rolls.

The dnd5e system uses a custom roll in combat.js: https://gitlab.com/foundrynet/dnd5e/-/blob/master/module/combat.js

```typescript
export const _getInitiativeFormula = function(combatant) {
  const actor = combatant.actor;
  if ( !actor ) return "1d20";
  const init = actor.data.data.attributes.init;
  const parts = ["1d20", init.mod, (init.prof !== 0) ? init.prof : null, (init.bonus !== 0) ? init.bonus : null];
  if ( actor.getFlag("dnd5e", "initiativeAdv") ) parts[0] = "2d20kh";
  if ( CONFIG.Combat.initiative.tiebreaker ) parts.push(actor.data.data.abilities.dex.value / 100);
  return parts.filter(p => p !== null).join(" + ");
};
```
It might be easier in both systems to hand this off to the combat tracker function in core but I don't know enough about how that operates yet.

**Comment by kakaroto** [comment]
Thanks for the research.

Humm.. I think this means that dnd5e has a bug in its system.json. as it does this specifies the initiative formula as : `1d20 + @abilities.dex.mod + @attributes.init.value + (@abilities.dex.value / 100)`
(see initiative field in https://gitlab.com/foundrynet/dnd5e/-/blob/master/system.json)

It should really just be `1d20 + @attributes.init.mod + @attributes.init.prof + @attributes.init.bonus + (@abilities.dex.value / 100)`

The only two things it does differently in that combat override is that it only adds the tie breaker based on a config, and it checks a "initiative advantage" setting to use 2d20kh1 instead of 1d20.
Those can't be programmed into the formula, but yeah, the formula itself is broken as it does `dex.mod + init.value` instead of `init.mod + init.prof + init.bonus`
