### ISSUE TITLE
Modifiers

### ISSUE THREAD

**Issue by Sparkasaurusmex** [kakaroto/fvtt-module-lmrtfy#24]
It would be nice to be able to add a modifier to a save if not automated.  Just a modifier field for the player in the pop up would suffice.

**Comment by LimpingNinja** [comment]
This may be added as a side-effect of the PF2e changes once approved which will add a drop-down item to query the player for mods/adv/disadv as if they rolled with that option: https://github.com/kakaroto/fvtt-module-lmrtfy/pull/25

**Comment by kakaroto** [comment]
Agreed, thanks to the changes added in #25, you can now set "Query Player" for the modifiers options and it will prompt the player for the situational bonus.
![image](https://user-images.githubusercontent.com/27990/88865183-307da000-d1d5-11ea-9395-5caf7ce20912.png)

![image](https://user-images.githubusercontent.com/27990/88865189-34a9bd80-d1d5-11ea-9445-5b966fd4ca8b.png)
