### ISSUE TITLE
PFR: Separate wording for roll types that have system dependent namings

### ISSUE THREAD

**Issue by LimpingNinja** [kakaroto/fvtt-module-lmrtfy#28]
Advantage/Disadvantage
Fortune/Misfortune
Death Savings Throw
Death Recovery Check
---

The question is what is the best way to handle this? It might be an idea to have the localization handle them based on system type:

`LMRTFY.${game.system.id}.DeathSaveRollMessage`

The 5E Japanese system doesn't need the PF2e messages, either.

Question: How is this normally handled in systems, is the above method a good way and if so, should it be minimal required message changes? I think yes, even if it gives me a brief tinge of anxiety.

**Comment by kakaroto** [comment]
i'm not sure a message per system makes sense... initiative is initiative 🤷 I wouldn't want to have to do "LMRTFY.DND5E.InitiativeMessage" and "LMRTFY.PF2E.InitiativeMessage" and "LMRTFY.PF1.InitiativeMessage", etc.. all for the same string.
I think if there is a need and it's a different kind of message/save, then that would need to be handled differently.. i.e: "InitiativeMessage" vs "SpecialPF1InitiativeMessage"

**Comment by kakaroto** [comment]
Unless there's anything further here, I'm closing this issue, feel free to reopen if there's a need.
