### ISSUE TITLE
Rolling with Advantage/Disadvantage mixed-up

### ISSUE THREAD

**Issue by nougvt** [kakaroto/fvtt-module-lmrtfy#30]
If advantage is chosen it rolls with disadvantage, vice versa

**Comment by kakaroto** [comment]
Good catch, thanks for the report!
@LimpingNinja can you confirm that it's inverted for PF2E as well, or if it's only dnd5e?

**Comment by LimpingNinja** [comment]
Only affects 5e for the Adv/Disadv roll, it should be

```
            LMRTFY.advantageRollEvent = { shiftKey: false, altKey: true, ctrlKey: false };
            LMRTFY.disadvantageRollEvent = { shiftKey: false, altKey: false, ctrlKey: true };
```

Must have slipped past the day I forgot my gingko biloba. I will open a PR for it.

**Comment by kakaroto** [comment]
Thanks for confirming, I'll do the fix right now directly from github :)
